/// Generated by AssetsRefGenerator on 2022/03/09
class Res {
  static const String appIcon = "assets/images/application_icon.png";
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String google = "assets/images/google.svg";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoSvg = "assets/images/logoSvg.svg";
  static const String appLogo = "assets/images/app_logo.svg";
  static const String check = "assets/images/check.svg";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String password = "assets/images/password.svg";
  static const String offline = "assets/images/offline.png";
  static const String appLoaderBg = "assets/images/appLoaderBg.png";
  static const String errorSnackBar = "assets/images/error_snack_bar.svg";
  static const String warningSnackBar = "assets/images/warning_snack_bar.svg";
  static const String successSnackBar = "assets/images/success_snack_bar.svg";
  static const String shortArrow = "assets/images/icons/short_arrow.svg";
  static const String arrowForward = "assets/images/icons/arrow_forward_icon.svg";
  static const String personIcon = "assets/images/person_icon.svg";
  static const String outlineNotification = "assets/images/icons/notification_outline_icon.svg";
  static const String paymentCards = "assets/images/icons/payment_cards_icon.svg";
  static const String pencilIcon = "assets/images/icons/pencil_icon.svg";
  static const String walletImage = "assets/images/wallet_image.png";
  static const String contactUs = "assets/images/icons/contact_us.svg";
  static const String globalIcon = "assets/images/icons/global_icon.svg";
  static const String lockIcon = "assets/images/icons/lock_icon.svg";
  static const String mapIcon = "assets/images/icons/map_icon.svg";
  static const String orderHistory = "assets/images/icons/order_history_icon.svg";
  static const String ordersStatistics = "assets/images/icons/orders_statistics_icon.svg";
  static const String privacyPolicy = "assets/images/icons/privacy_policy.svg";
  static const String termsConditions = "assets/images/icons/terms_conditions_icon.svg";
  static const String invertedTriangle = "assets/images/icons/inveirted_triangle_icon.svg";
  static const String filterIcon = "assets/images/icons/filter_icon.svg";
  static const String sulitLogo = "assets/images/sulit_logo.png";
  static const String boxIcon = "assets/images/box_icon.svg";
  static const String closeIcon = "assets/images/icons/close_icon.svg";
  static const String tikTokIcon = "assets/images/icons/tik_tok_icon.svg";
  static const String twitterIcon = "assets/images/icons/twitter_icon.svg";
  static const String instagramIcon = "assets/images/icons/instagram.png";
  static const String whatsappIcon = "assets/images/icons/whatsapp_icon.svg";
  static const String beefImage = "assets/images/beef.jpg";
  static const String chickenImage = "assets/images/chicken.jpg";
  static const String milk = "assets/images/milk.jpg";
  static const String organicMilk = "assets/images/organic_milk.jpg";
  static const String appPickerSvg = "assets/images/app_picker.svg";
  static const String sulitTitleImage = "assets/images/suliit_title_image.png";

  // Home screen assets that already exist in assets/images/
  static const String headerIcon = "assets/images/header-icon.svg";
  static const String notificationIconHome = "assets/images/notification-icon.svg";
  static const String searchIconHome = "assets/images/search-icon.svg";
  static const String sectionIcon1 = "assets/images/section-icon-1.svg";
  static const String sectionIcon2 = "assets/images/section-icon-2.svg";
  static const String markerIcon = "assets/images/marker_icon.svg";
  static const String iconMiddleRight = "assets/images/icon-middle-right.svg";
  static const String iconRight = "assets/images/icon-right.svg";
  static const String iconFarRight = "assets/images/icon-far-right.svg";
  static const String returnOrderIcon = "assets/images/return_order_icon.svg";
  static const String notificationBill = "assets/images/illustrations/notification_bill.gif";

  // New driver app icons
  static const String deliveryIcon = "assets/images/icons/delivery_icon.svg";
  static const String walletIcon = "assets/images/icons/wallet_icon.svg";
  static const String statisticsIcon = "assets/images/icons/statistics_icon.svg";
  static const String ordersIcon = "assets/images/icons/orders_icon.svg";
  static const String notificationIcon = "assets/images/icons/notification_icon.svg";
  static const String contactIcon = "assets/images/icons/contact_icon.svg";
  static const String termsIcon = "assets/images/icons/terms_icon.svg";
  static const String privacyIcon = "assets/images/icons/privacy_icon.svg";
  static const String subscriptionIcon = "assets/images/icons/subscription_icon.svg";
  static const String logoutIcon = "assets/images/icons/logout_icon.svg";
  static const String profileIcon = "assets/images/icons/profile_icon.svg";
  static const String menuIcon = "assets/images/icons/menu_icon.svg";
  // static const String sulitIcon = "assets/images/icons/sulit_icon.png";
  static const String appSlogan = "assets/images/Weideliver.svg";
  static const String warningIcon = "assets/images/warning_icon.svg";

  //auth
  static const String forgetPassBackground = "assets/images/forgetpass_background.png";
  static const String appSloganPng = "assets/images/app_slogan.png";

  // Home screen specific icons
  static const String homeNotification = "assets/images/icons/home_notification.svg";
  static const String homeProfile = "assets/images/icons/home_profile.svg";
  static const String locationIcon = "assets/images/icons/location_icon.svg";
  static const String phoneIcon = "assets/images/icons/phone_icon.svg";
  static const String searchIcon = "assets/images/icons/search_icon.svg";
  static const String checkIcon = "assets/images/icons/check_icon.svg";
  static const String noOrdersAvailable = "assets/images/no_orders_available.png";

  // Illustrations
  static const String noOrdersIllustration = "assets/images/illustrations/no_orders.svg";
  static const String orderAlertIllustration = "assets/images/illustrations/order_alert.svg";
  static const String welcomeDialogIllustration = "assets/images/illustrations/welcome_dialog_illustration.svg";
  static const String doneImage = "assets/images/done_image.svg";

  // sounds
  static const String newOrderSound = "assets/sounds/bell_ring.mp3";
}
